services:
  cassavamarketplace:
    container_name: cassavamarketplace
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - "3500:3000"
    volumes:
      - .:/app
      - /app/node_modules # Empêche la perte des dépendances
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
