services:
  cassavamarketplace:
    container_name: cassavamarketplace
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.local
    ports:
      - "3500:3000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true  # Utiliser le réseau partagé existant
