services:
  cassavamarketplace_uat:
    container_name: cassavamarketplace_uat
    build:
      context: .
      dockerfile: Dockerfile.uat
    restart: always
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
    ports:
      - "3501:3000"
    volumes:
      - /var/www/cassavamarketplace/static_uat:/mnt/static
    networks:
      - shared-network

networks:
  shared-network:
    external: true  # Utiliser le réseau partagé existant
