services:
  cassavamarketplace_uat:
    container_name: cassavamarketplace_uat
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.uat
    ports:
      - "3501:3000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true  # Utiliser le réseau partagé existant
