services:
  cassavamarketplace:
    container_name: cassavamarketplace
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    env_file:
      - .env.local
    ports:
      - "3500:3000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true  # Utiliser le réseau partagé existant
