services:
  cassavamarketplace_uat:
    container_name: cassavamarketplace_uat
    build:
      context: .
      dockerfile: Dockerfile.uat
    env_file:
      - .env.uat
    ports:
      - "3501:3000"
    volumes:
      - .:/app
      - /app/node_modules # Empêche la perte des dépendances
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
